using UnityEditor.SceneManagement;
using UnityEditor;
using UnityEngine;
using System.Linq;
using System.IO;

public static class AutoSceneSetup
{
    private static string scenePath = "Assets/AutoGeneratedScene.unity";

    public static void CreateAutoScene()
    {
        if (File.Exists(scenePath))
            return; // ”же есть

        var newScene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        var cameraGO = new GameObject("Main Camera");
        var camera = cameraGO.AddComponent<Camera>();
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = Color.black;
        camera.orthographic = true;
        cameraGO.tag = "MainCamera";

        var go = new GameObject("AutoGeneratedGO");
        go.AddComponent<ShowPageScreen>();

        EditorSceneManager.MarkSceneDirty(newScene);

        bool saveOk = EditorSceneManager.SaveScene(newScene, scenePath);
        if (!saveOk)
            throw new System.Exception("Failed to save autoscene");

        var buildScenes = EditorBuildSettings.scenes.ToList();
        if (!buildScenes.Any(s => s.path == scenePath))
        {
            buildScenes.Insert(0, new EditorBuildSettingsScene(scenePath, true));
            EditorBuildSettings.scenes = buildScenes.ToArray();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        Debug.Log("? Auto scene created and added to the build.");
    }
}
